---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: inline
---  

```{r}
library(PRP)
library(rstudioapi)
library(mamba)
library(data.table)
library(parallel)
library(knitr)
library(pander)
library(ggplot2)
library(tidyverse)

setwd(dirname(rstudioapi::getActiveDocumentContext()$path))

set.seed(2021)
```

Some functions to determine our true positive rates and false positive rates.
```{r}
true_false_pos_rate <- function(out_studies, pred) {
  
  # truth, SNP that actually contains outliers
  actual <- rowSums(out_studies == 0) > 0
  
  # true and false positives
  tpos <- (actual == pred) & (actual == TRUE)
  fpos <- ((actual == FALSE) == pred) & (actual == FALSE)
  
  # false positive rate
  fpos_count <- length(fpos[fpos == TRUE])
  act_neg_count <- length(actual[actual == FALSE])
  fpr <- fpos_count/act_neg_count
  
  
  # true positive rate
  tpos_count <- length(tpos[tpos == TRUE])
  act_pos_count <- length(actual[actual == TRUE])
  tpr <- tpos_count/act_pos_count
  return(c(fpr, tpr))
}
```

```{r}
roc_rates <- function(contain_outlier, # actual outliers
                      mamba_ppr_val, # vector of mamba ppr values
                      prp_val, # vector of prp values
                      interval = 0.05) {
  
  mamba_ppr_rates <- list()
  prp_rates <- list()
  
  # iterate through different cutoffs
  for (cutoff in seq(from = 0, to = 1, by = interval)) {
    
    # outlier or not based on cutoff
    mamba_ppr_pred <- mamba_ppr_val < cutoff
    prp_pred <- prp_val < cutoff
    
    
    
    mamba_ppr_rates <- rbind(mamba_ppr_rates,
                             true_false_pos_rate(contain_outlier,
                                                 mamba_ppr_pred))
    
    
    prp_rates <- rbind(prp_rates,
                       true_false_pos_rate(contain_outlier,
                                           prp_pred))
  }
  
  rates_list <- list("mamba_ppr_rates" = mamba_ppr_rates, "prp_rates" = prp_rates)
  return(rates_list)
}
```

# 0.9 nonoutlier rate

Looking at p90
```{r}
load(file = "../data/post_prp_data_pval_p90.rda")
load(file = "../data/sim_mamba_mod_p90.rda")
load(file = "../data/mamba_data_p90.rda")

p90_outliers <- mamba_data_p90$Ojk
p90_mamba_ppr <- sim_mod_p90$ppr
p90_prp <- post_prp_data_pval_p90
```

```{r}
p90_rates <- roc_rates(contain_outlier = p90_outliers,
                       mamba_ppr_val = p90_mamba_ppr,
                       prp_val = p90_prp,
                       interval = 0.0005)
```

ROC Plots
```{r}
plot(p90_rates$mamba_ppr_rates)
```

```{r}
plot(p90_rates$prp_rates)
```

# 0.75 nonoutlier rate
Looking at p75
```{r}
load(file = "../data/post_prp_data_pval_p75.rda")
load(file = "../data/sim_mamba_mod_p75.rda")
load(file = "../data/mamba_data_p75.rda")

p75_outliers <- mamba_data_p75$Ojk
p75_mamba_ppr <- sim_mod_p75$ppr
p75_prp <- post_prp_data_pval_p75
```

```{r}
p75_rates <- roc_rates(contain_outlier = p75_outliers,
                       mamba_ppr_val = p75_mamba_ppr,
                       prp_val = p75_prp,
                       interval = 0.0005)
```

The ROC plots are:
```{r}
plot(p75_rates$mamba_ppr_rates)
```


```{r}
plot(p75_rates$prp_rates)
```

```{r}
hist(p75_prp)
```

